spring:
  profiles:
    active: test
 

    config:
     activate:
       on-profile:dev
   

  datasource:
    url: jdbc:mysql:///system
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: shank
    dbcp2:
      max-total: 100
      initial-size: 10
      max-conn-lifetime-millis: 100000
    type: org.apache.commons.dbcp2.BasicDataSource
